from langchain.tools import tool
from schema.Agent import State


@tool
def read_plan(state:State):
    """use this tool to read all plan generated by supervisor agent"""
    print(f"📖 Shared read_plan called: {state['plans']}")
    if len(state['plans'].keys()) == 0:
        return "There are no todo plans as of now, please respond with normally"
    else:
        return state['plans']