from langchain.tools import tool
from graph.agent import State


@tool
def write_plan(plan:str,status:str,state:State):
    """use this tool to write all plan generated by supervisor agent"""
    print(f"✍️ Shared write_plan called: {plan} -> {status}")
    state["plans"][plan] = status   
    return "plans written successfully"